### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by DaRealAqua** [ethaniccc/SlapperPlayerCount#5]
[Asynchronous Worker #1 thread/CRITICAL]: ErrorException: "A non well formed numeric value encountered" (EXCEPTION) in "plugins/CrossOnlineCount-master/src/libpmquery/PMQuery" at line 13

if i add like /slapper spawn human TEST ip:port it show only Server offline

but if i do /slapper spawn human ip:port work but only the members it show

**Comment by ethaniccc** [comment]
> [Asynchronous Worker #1 thread/CRITICAL]: ErrorException: "A non well formed numeric value encountered" (EXCEPTION) in "plugins/CrossOnlineCount-master/src/libpmquery/PMQuery" at line 13

Separate issue that I will also look into

Please download the fix I made a few minutes ago: https://poggit.pmmp.io/r/86902/CrossOnlineCount_dev-13.phar

> if i add like /slapper spawn human TEST ip:port it show only Server offline
> but if i do /slapper spawn human ip:port work but only the members it show

This has also been fixed in the new update

Read the README for the new instructions: https://github.com/ethaniccc/CrossOnlineCount/blob/master/README.md

If there are any more bugs, feel free to report them

**Comment by ethaniccc** [comment]
For the 1st error mentioned, it was probably an error when typing the command. If it's not, please comment on here again for me to reopen the issue.

Stable Version: https://poggit.pmmp.io/p/SlapperPlayerCount
